# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ITrip' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

pod 'Alamofire','=3.4.1'

end
#sudo gem install cocoapods -v 1.0.0