# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ITrip' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

pod 'Alamofire','=3.4.1'
pod 'SnapKit','=0.21.1'
pod 'FlatColor'
pod 'ChameleonFramework/Swift'
pod 'JMEParallaxView'
pod 'MXParallaxHeader'
pod 'ASJTagsView'
pod 'IQKeyboardManager'

pod 'ActionSheetPicker-3.0'


pod 'SwiftyJSON', '2.4.0'
pod 'ReachabilitySwift', '~> 2.4'
pod 'CWStatusBarNotification'


end
#sudo gem install cocoapods -v 1.0.0
